"""Generate funny names"""

import sys
import random

def main():
    """Return random names generated by the two lists"""
    print("Welcome to the Psych 'Sidekick Name Picker'")
    print("A name just like Sean would pick for Gus:\n\n")
    first = ('Baby Oil','Bad News', 'Big Burps', "Bill 'Beenie-Weenie'", "Bob 'Stinkbug'",
             'Bowel Noises','Boxelder',
             'Bud Lite','Butterbean','Buttermilk','Buttocks','Chad','Chesterfield','Crapps',
             'Dark Skies','Dennis Clawhammer', 'Dicman','Elphonso','Mergatroid','Mr Peabody',
             'Joe PottinSoil','Schlomo','Sweet Tea','Teetee','Squids','Stinky',
             'ZeeZoo','Worms','XeeXio','Winston','Jazz Hands')
    last = ('Appleyard','Bigmeat','Bloominshine','Boogerbottom',
            'Breedslovetrout','Cocktoasten','Endicott','Henderson','Guster',
            'Fewhairs','Gooberdapple','Hoosenater','Hootkins',
            'Jefferson','Jingley-Schmidt', 'Kingfish','Listenbee','Oxhandler',
            'Peaklike','Beaklike','Walkingstick','WallBanger','Weewax','Beezax','Vinaigrette',
            'Quackenbush','Quacksalot','Pieplow',
            'Zingleberry','Freshenchime','Wimplesnatch','Winterkorn','Woolysocks')
    while True:
        firstname = random.choice(first)
        lastname = random.choice(last)
        print('\n\n')
        print("{} {}".format(firstname, lastname), file=sys.stderr)
        print("\n\n")
        try_again = input("Try again? (Press Enter else n to quit)\n")
        if try_again.lower() == "n":
            break
    input("\nPress Enter to exit.")
if __name__ == '__main__':
    main()
